# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyvideo_tools',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/pyvideo_tools',
                'lib_path': 'pyvideo_tools'},
  'syms': {'pyvideo_tools.core': {'pyvideo_tools.core.foo': ('core.html#foo', 'pyvideo_tools/core.py')}}}
