# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyvideo-tools',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/pyvideo-tools',
                'lib_path': 'pyvideo'},
  'syms': {'pyvideo.core': {'pyvideo.core.foo': ('core.html#foo', 'pyvideo/core.py')}}}
